name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Явно указываем права на запись
      pages: write # Права для GitHub Pages
      id-token: write # Для аутентификации

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install HTML validator
        run: |
          sudo apt-get update
          sudo apt-get install -y tidy

      - name: Validate HTML files
        run: |
          find . -name "*.html" -exec tidy -q -e {} \;
        continue-on-error: true

      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: . # Деплоим файлы из корня
