name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install Qt and tools
      run: |
        sudo apt-get update
        sudo apt install -y qtcreator qtbase5-dev qt5-qmake cmake
        sudo apt-get install -y qt6-base-dev qt6-declarative-dev cmake g++ ninja-build lcov xvfb
    - name: Prepare build directory
      run: |
        if [ ! -d build ]; then mkdir build; fi
    - name: Configure CMake
      run: |
        cd build
        cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="--coverage"
